name: Main

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v3
    - name: install-deps
      run: sudo apt-get update && sudo apt-get install build-essential
    - name: build
      run: gcc -o main main.c
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0'
    - run: bundle install --path vendor/bundle 
    - name: run tests
      run: bundle exec rspec